import { useState, useMemo } from 'react';
import { QUIZ_QUESTIONS, SHAKTI_PEETHAS, VERSE_PUZZLES } from '@/data/content';
import { Check, X, Trophy, MapPin, RotateCcw, Gamepad2 } from 'lucide-react';

type GameMode = 'menu' | 'trivia' | 'peetha' | 'verse';

export function ArenaPage() {
  const [mode, setMode] = useState<GameMode>('menu');
  if (mode === 'menu') { return (<div className="space-y-6 animate-fadeIn"><div><h1 className="section-title text-3xl text-accent mb-2">Quiz Arena & Mini-Games</h1><p className="text-muted text-sm">Test your knowledge of Puranic lore, iconography, and sacred geography.</p></div><div className="grid sm:grid-cols-3 gap-4"><button onClick={() => setMode('trivia')} className="card p-6 text-left hover:border-[var(--accent)] transition-all group"><div className="h-11 w-11 rounded-xl bg-card2 flex items-center justify-center mb-3 group-hover:shadow-glow"><Trophy className="h-5 w-5 text-accent" /></div><h3 className="font-semibold mb-1">Puranic Trivia</h3><p className="text-xs text-muted">Test your knowledge of deities, weapons, and mounts.</p></button><button onClick={() => setMode('peetha')} className="card p-6 text-left hover:border-[var(--accent)] transition-all group"><div className="h-11 w-11 rounded-xl bg-card2 flex items-center justify-center mb-3 group-hover:shadow-glow"><MapPin className="h-5 w-5 text-accent" /></div><h3 className="font-semibold mb-1">Match the Shakti Peetha</h3><p className="text-xs text-muted">Match body parts and deities to sacred locations.</p></button><button onClick={() => setMode('verse')} className="card p-6 text-left hover:border-[var(--accent)] transition-all group"><div className="h-11 w-11 rounded-xl bg-card2 flex items-center justify-center mb-3 group-hover:shadow-glow"><Gamepad2 className="h-5 w-5 text-accent" /></div><h3 className="font-semibold mb-1">Verse Assembly</h3><p className="text-xs text-muted">Rearrange jumbled lines of famous stotrams.</p></button></div></div>); }
  return (<div><button onClick={() => setMode('menu')} className="btn-ghost px-4 py-2 text-sm mb-4">Back to Arena</button>{mode === 'trivia' && <TriviaGame />}{mode === 'peetha' && <PeethaGame />}{mode === 'verse' && <VerseGame />}</div>);
}

function TriviaGame() {
  const [idx, setIdx] = useState(0); const [selected, setSelected] = useState<number | null>(null); const [score, setScore] = useState(0); const [done, setDone] = useState(false);
  const q = QUIZ_QUESTIONS[idx];
  const choose = (i: number) => { if (selected !== null) return; setSelected(i); if (i === q.answer) setScore(score + 1); setTimeout(() => { if (idx < QUIZ_QUESTIONS.length - 1) { setIdx(idx + 1); setSelected(null); } else { setDone(true); } }, 1500); };
  if (done) { return (<div className="card p-8 text-center max-w-md mx-auto"><Trophy className="h-12 w-12 text-gold mx-auto mb-4" /><h2 className="section-title text-2xl text-accent mb-2">Quiz Complete</h2><p className="text-lg mb-4">You scored {score} / {QUIZ_QUESTIONS.length}</p><button onClick={() => { setIdx(0); setScore(0); setSelected(null); setDone(false); }} className="btn-primary px-5 py-2.5 text-sm flex items-center gap-2 mx-auto"><RotateCcw className="h-4 w-4" /> Play Again</button></div>); }
  return (<div className="card p-6 max-w-xl mx-auto"><div className="flex items-center justify-between mb-4"><span className="chip">Question {idx + 1} / {QUIZ_QUESTIONS.length}</span><span className="chip">Score: {score}</span></div><p className="text-xs text-accent mb-1">{q.category}</p><h2 className="text-lg font-semibold mb-5">{q.question}</h2><div className="space-y-2">{q.options.map((opt, i) => { const isCorrect = i === q.answer; const isSelected = selected === i; let cls = 'card-2 p-3.5 text-left text-sm hover:border-[var(--accent)] transition-all'; if (selected !== null) { if (isCorrect) cls = 'card-2 p-3.5 text-left text-sm border-emerald-500/50 bg-emerald-500/10'; else if (isSelected) cls = 'card-2 p-3.5 text-left text-sm border-red-500/50 bg-red-500/10'; else cls = 'card-2 p-3.5 text-left text-sm opacity-50'; } return (<button key={i} onClick={() => choose(i)} className={cls + ' w-full flex items-center justify-between'}><span>{opt}</span>{selected !== null && isCorrect && <Check className="h-4 w-4 text-emerald-400" />}{selected !== null && isSelected && !isCorrect && <X className="h-4 w-4 text-red-400" />}</button>); })}</div>{selected !== null && <p className="text-xs text-muted mt-4 italic">{q.explanation}</p>}</div>);
}

function PeethaGame() {
  const shuffled = useMemo(() => [...SHAKTI_PEETHAS].sort(() => Math.random() - 0.5).slice(0, 5), []);
  const [idx, setIdx] = useState(0); const [selected, setSelected] = useState<number | null>(null); const [score, setScore] = useState(0); const [done, setDone] = useState(false);
  const current = shuffled[idx];
  const options = useMemo(() => { if (!current) return []; const others = SHAKTI_PEETHAS.filter((p) => p.id !== current.id).sort(() => Math.random() - 0.5).slice(0, 3); return [...others, current].sort(() => Math.random() - 0.5); }, [idx, current]);
  if (!current) return null;
  const choose = (i: number) => { if (selected !== null) return; setSelected(i); if (options[i].id === current.id) setScore(score + 1); setTimeout(() => { if (idx < shuffled.length - 1) { setIdx(idx + 1); setSelected(null); } else { setDone(true); } }, 1500); };
  if (done) { return (<div className="card p-8 text-center max-w-md mx-auto"><MapPin className="h-12 w-12 text-gold mx-auto mb-4" /><h2 className="section-title text-2xl text-accent mb-2">Game Complete</h2><p className="text-lg mb-4">You matched {score} / {shuffled.length}</p><button onClick={() => { setIdx(0); setScore(0); setSelected(null); setDone(false); }} className="btn-primary px-5 py-2.5 text-sm flex items-center gap-2 mx-auto"><RotateCcw className="h-4 w-4" /> Play Again</button></div>); }
  return (<div className="card p-6 max-w-xl mx-auto"><div className="flex items-center justify-between mb-4"><span className="chip">Peetha {idx + 1} / {shuffled.length}</span><span className="chip">Score: {score}</span></div><p className="text-xs text-accent mb-1">Match this Shakti Peetha:</p><h2 className="text-lg font-semibold mb-1">{current.name}</h2><p className="text-sm text-muted mb-1">Body part: {current.bodyPart}</p><p className="text-sm text-muted mb-5">Deity: {current.deity}</p><p className="text-xs text-muted mb-2">Where is it located?</p><div className="space-y-2">{options.map((opt, i) => { const isCorrect = opt.id === current.id; const isSelected = selected === i; let cls = 'card-2 p-3.5 text-left text-sm hover:border-[var(--accent)] transition-all w-full'; if (selected !== null) { if (isCorrect) cls = 'card-2 p-3.5 text-left text-sm border-emerald-500/50 bg-emerald-500/10 w-full'; else if (isSelected) cls = 'card-2 p-3.5 text-left text-sm border-red-500/50 bg-red-500/10 w-full'; else cls = 'card-2 p-3.5 text-left text-sm opacity-50 w-full'; } return (<button key={opt.id} onClick={() => choose(i)} className={cls}>{opt.location} <span className="text-muted text-xs">({opt.region})</span></button>); })}</div></div>);
}

function VerseGame() {
  const [puzzleIdx, setPuzzleIdx] = useState(0); const [order, setOrder] = useState<number[]>([]); const [done, setDone] = useState(false);
  const puzzle = VERSE_PUZZLES[puzzleIdx];
  const reset = () => { setOrder(puzzle.lines.map((_, i) => i).sort(() => Math.random() - 0.5)); setDone(false); };
  useMemo(() => { setOrder(puzzle.lines.map((_, i) => i).sort(() => Math.random() - 0.5)); }, [puzzleIdx]);
  const moveUp = (i: number) => { if (i === 0 || done) return; const newOrder = [...order]; [newOrder[i - 1], newOrder[i]] = [newOrder[i], newOrder[i - 1]]; setOrder(newOrder); };
  const moveDown = (i: number) => { if (i === order.length - 1 || done) return; const newOrder = [...order]; [newOrder[i + 1], newOrder[i]] = [newOrder[i], newOrder[i + 1]]; setOrder(newOrder); };
  const check = () => { const correct = order.every((v, i) => v === puzzle.correctOrder[i]); setDone(true); if (correct && navigator.vibrate) navigator.vibrate([100, 50, 100]); };
  const isCorrect = done && order.every((v, i) => v === puzzle.correctOrder[i]);
  return (<div className="card p-6 max-w-xl mx-auto"><div className="flex items-center justify-between mb-4"><span className="chip">Puzzle {puzzleIdx + 1} / {VERSE_PUZZLES.length}</span><button onClick={() => { if (puzzleIdx < VERSE_PUZZLES.length - 1) { setPuzzleIdx(puzzleIdx + 1); } else { setPuzzleIdx(0); } }} className="chip">Next Puzzle</button></div><h2 className="text-lg font-semibold mb-1">{puzzle.title}</h2><p className="text-xs text-muted mb-5">Arrange the lines in the correct sequence.</p><div className="space-y-2">{order.map((lineIdx, i) => { const isRight = done && lineIdx === puzzle.correctOrder[i]; return (<div key={i} className={`card-2 p-3 flex items-center justify-between ${isRight ? 'border-emerald-500/50 bg-emerald-500/10' : ''}`}><span className="deva text-sm flex-1">{puzzle.lines[lineIdx]}</span><div className="flex gap-1 ml-2"><button onClick={() => moveUp(i)} className="btn-ghost px-2 py-1 text-xs">↑</button><button onClick={() => moveDown(i)} className="btn-ghost px-2 py-1 text-xs">↓</button></div></div>); })}</div>{!done ? (<button onClick={check} className="btn-primary w-full py-2.5 text-sm mt-5">Check Order</button>) : (<div className="mt-5">{isCorrect ? (<p className="text-emerald-400 text-sm flex items-center gap-2"><Check className="h-4 w-4" /> Correct! The verses are in the right order.</p>) : (<p className="text-red-400 text-sm flex items-center gap-2"><X className="h-4 w-4" /> Not quite. Try again.</p>)}<button onClick={reset} className="btn-ghost px-4 py-2 text-sm mt-3 flex items-center gap-2"><RotateCcw className="h-4 w-4" /> Reset</button></div>)}</div>);
}
