import { useState, useEffect } from 'react';
import { getJournal, saveJournalEntry, deleteJournalEntry, addToHistory } from '@/lib/storage';
import { BookOpen, Plus, Trash2, Calendar, Save, X } from 'lucide-react';
import type { JournalEntry } from '@/types';

export function JournalPage() {
  const [entries, setEntries] = useState<JournalEntry[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState<JournalEntry | null>(null);
  useEffect(() => { setEntries(getJournal()); addToHistory('Sadhana Journal'); }, []);
  const blankEntry = (): JournalEntry => ({ id: Date.now().toString(), date: new Date().toISOString().split('T')[0], mantra: '', mood: '', dreams: '', meditation: '', insights: '', questions: '', gratitude: '' });
  const [form, setForm] = useState<JournalEntry>(blankEntry());
  const startNew = () => { setEditing(null); setForm(blankEntry()); setShowForm(true); };
  const startEdit = (e: JournalEntry) => { setEditing(e); setForm(e); setShowForm(true); };
  const save = () => { const updated = saveJournalEntry(form); setEntries(updated); setShowForm(false); setEditing(null); };
  const remove = (id: string) => { const updated = deleteJournalEntry(id); setEntries(updated); };
  const moods = ['Peaceful', 'Devoted', 'Restless', 'Grateful', 'Contemplative', 'Energetic', 'Quiet', 'Challenged'];
  return (
    <div className="space-y-6 animate-fadeIn">
      <div className="flex items-start justify-between"><div><h1 className="section-title text-3xl text-accent mb-2">Sadhana Journal</h1><p className="text-muted text-sm">Track your daily practice, mood, insights, and spiritual journey. All data stays on your device — no account needed.</p></div>{!showForm && (<button onClick={startNew} className="btn-primary px-4 py-2.5 text-sm flex items-center gap-2 shrink-0"><Plus className="h-4 w-4" /> New Entry</button>)}</div>
      {showForm && (<div className="card p-6 animate-slideUp"><div className="flex items-center justify-between mb-4"><h2 className="section-title text-lg text-accent">{editing ? 'Edit Entry' : 'New Journal Entry'}</h2><button onClick={() => setShowForm(false)} className="btn-ghost p-2"><X className="h-4 w-4" /></button></div><div className="space-y-4"><div><label className="text-xs text-muted block mb-1">Date</label><input type="date" className="input-field" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></div><div><label className="text-xs text-muted block mb-2">Mood</label><div className="flex flex-wrap gap-2">{moods.map((m) => (<button key={m} onClick={() => setForm({ ...form, mood: m })} className={`chip ${form.mood === m ? 'chip-active' : ''}`}>{m}</button>))}</div></div><div><label className="text-xs text-muted block mb-1">Mantra / Japa Practice</label><input className="input-field" value={form.mantra} onChange={(e) => setForm({ ...form, mantra: e.target.value })} placeholder="e.g., Om Namah Shivaya x108" /></div><div><label className="text-xs text-muted block mb-1">Meditation</label><textarea className="input-field min-h-[60px]" value={form.meditation} onChange={(e) => setForm({ ...form, meditation: e.target.value })} placeholder="Duration, technique, observations..." /></div><div><label className="text-xs text-muted block mb-1">Dreams</label><textarea className="input-field min-h-[60px]" value={form.dreams} onChange={(e) => setForm({ ...form, dreams: e.target.value })} placeholder="Notable dreams or visions..." /></div><div><label className="text-xs text-muted block mb-1">Insights</label><textarea className="input-field min-h-[80px]" value={form.insights} onChange={(e) => setForm({ ...form, insights: e.target.value })} placeholder="What did you realize or understand today?" /></div><div><label className="text-xs text-muted block mb-1">Questions for the Guru</label><textarea className="input-field min-h-[60px]" value={form.questions} onChange={(e) => setForm({ ...form, questions: e.target.value })} placeholder="Doubts, questions, things to explore..." /></div><div><label className="text-xs text-muted block mb-1">Gratitude</label><textarea className="input-field min-h-[60px]" value={form.gratitude} onChange={(e) => setForm({ ...form, gratitude: e.target.value })} placeholder="What are you grateful for today?" /></div><button onClick={save} className="btn-primary w-full py-2.5 text-sm flex items-center justify-center gap-2"><Save className="h-4 w-4" /> Save Entry</button></div></div>)}
      {entries.length === 0 && !showForm ? (<div className="card p-12 text-center"><BookOpen className="h-12 w-12 text-muted mx-auto mb-4" /><h3 className="font-semibold mb-2">No journal entries yet</h3><p className="text-sm text-muted mb-4">Start documenting your spiritual journey today.</p><button onClick={startNew} className="btn-primary px-5 py-2.5 text-sm flex items-center gap-2 mx-auto"><Plus className="h-4 w-4" /> Write First Entry</button></div>) : (<div className="space-y-3">{entries.map((e) => (<div key={e.id} className="card p-5"><div className="flex items-start justify-between mb-3"><div className="flex items-center gap-2"><Calendar className="h-4 w-4 text-accent" /><span className="text-sm font-medium">{e.date}</span>{e.mood && <span className="chip text-[10px]">{e.mood}</span>}</div><div className="flex gap-1"><button onClick={() => startEdit(e)} className="btn-ghost p-1.5 text-xs">Edit</button><button onClick={() => remove(e.id)} className="btn-ghost p-1.5 text-xs text-red-400"><Trash2 className="h-3.5 w-3.5" /></button></div></div><div className="space-y-2 text-sm">{e.mantra && <p><span className="text-muted text-xs">Mantra:</span> {e.mantra}</p>}{e.meditation && <p><span className="text-muted text-xs">Meditation:</span> {e.meditation}</p>}{e.dreams && <p><span className="text-muted text-xs">Dreams:</span> {e.dreams}</p>}{e.insights && <p><span className="text-muted text-xs">Insights:</span> {e.insights}</p>}{e.questions && <p><span className="text-muted text-xs">Questions:</span> {e.questions}</p>}{e.gratitude && <p><span className="text-muted text-xs">Gratitude:</span> {e.gratitude}</p>}</div></div>))}</div>)}
    </div>
  );
}
