import { useState, useMemo } from 'react';
import { DEITIES, FOLK_NODES, SAMPRADAYAS, JYOTIRLINGAS, DASHAVATARA } from '@/data/content';
import type { Tradition, Deity, FolkNode } from '@/types';
import { SafetyBadge } from '@/components/SafetyBadge';
import { Modal } from '@/components/Modal';
import { ChevronRight, MapPin, Sword, Sparkles } from 'lucide-react';

const TABS: { id: Tradition | 'all'; label: string }[] = [{ id: 'all', label: 'All' },{ id: 'vaishnava', label: 'Vaishnava' },{ id: 'shaiva', label: 'Shaiva' },{ id: 'shakta', label: 'Shakta' },{ id: 'folk', label: 'Folk & Regional' },{ id: 'vedic', label: 'Vedic & Puranic' }];

interface Props { searchQuery: string; }

export function KnowledgePage({ searchQuery }: Props) {
  const [tab, setTab] = useState<Tradition | 'all'>('all');
  const [selected, setSelected] = useState<Deity | FolkNode | null>(null);
  const filteredDeities = useMemo(() => DEITIES.filter((d) => { const matchTab = tab === 'all' || d.tradition === tab; const q = searchQuery.toLowerCase(); const matchSearch = !q || d.name.toLowerCase().includes(q) || d.iast.toLowerCase().includes(q) || d.summary.toLowerCase().includes(q); return matchTab && matchSearch; }), [tab, searchQuery]);
  const filteredFolk = useMemo(() => { if (tab !== 'all' && tab !== 'folk') return []; const q = searchQuery.toLowerCase(); return FOLK_NODES.filter((f) => !q || f.name.toLowerCase().includes(q) || f.summary.toLowerCase().includes(q) || f.region.toLowerCase().includes(q)); }, [tab, searchQuery]);
  return (
    <div className="space-y-6 animate-fadeIn">
      <div><h1 className="section-title text-3xl text-accent mb-2">Knowledge Hub</h1><p className="text-muted text-sm">Explore deities, sampradayas, and regional folk traditions across Sanatana Dharma.</p></div>
      <div className="flex gap-2 overflow-x-auto no-scrollbar pb-1">{TABS.map((t) => (<button key={t.id} onClick={() => setTab(t.id)} className={`chip whitespace-nowrap ${tab === t.id ? 'chip-active' : ''}`}>{t.label}</button>))}</div>
      {(tab === 'all' || tab === 'vaishnava' || tab === 'shaiva' || tab === 'shakta') && (<section className="card p-5"><h2 className="section-title text-lg text-accent mb-4">Sampradayas & Schools</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{[...(tab === 'all' || tab === 'vaishnava' ? SAMPRADAYAS.vaishnava : []), ...(tab === 'all' || tab === 'shaiva' ? SAMPRADAYAS.shaiva : []), ...(tab === 'all' || tab === 'shakta' ? SAMPRADAYAS.shakta : [])].map((s, i) => (<div key={i} className="card-2 p-4"><h3 className="font-semibold text-sm text-accent mb-1">{s.name}</h3>{s.founder && <p className="text-xs text-muted mb-1">Founder: {s.founder}</p>}<p className="text-xs text-muted leading-relaxed">{s.focus}</p></div>))}</div></section>)}
      {(tab === 'all' || tab === 'shaiva') && (<section className="card p-5"><h2 className="section-title text-lg text-accent mb-4">The 12 Jyotirlingas</h2><div className="flex flex-wrap gap-2">{JYOTIRLINGAS.map((j, i) => (<span key={i} className="chip"><Sparkles className="h-3 w-3 text-gold" /> {j}</span>))}</div></section>)}
      {(tab === 'all' || tab === 'vaishnava') && (<section className="card p-5"><h2 className="section-title text-lg text-accent mb-4">Dashavatara</h2><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3">{DASHAVATARA.map((a, i) => (<div key={i} className="card-2 p-3 text-center"><div className="h-9 w-9 rounded-full bg-gold/15 flex items-center justify-center mx-auto mb-2"><span className="text-accent font-bold text-sm">{i + 1}</span></div><h3 className="font-semibold text-sm">{a.name}</h3><p className="text-[11px] text-muted">{a.form}</p><p className="text-[11px] text-muted mt-1 leading-snug">{a.purpose}</p></div>))}</div></section>)}
      <section><h2 className="section-title text-xl text-accent mb-4">Deities & Forms</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{filteredDeities.map((d) => (<button key={d.id} onClick={() => setSelected(d)} className="card p-5 text-left hover:border-[var(--accent)] transition-all hover:-translate-y-0.5"><div className="flex items-start justify-between gap-2 mb-2"><div><h3 className="font-semibold text-base">{d.name}</h3><p className="iast text-xs text-accent">{d.iast}</p></div><SafetyBadge level={d.safety} compact /></div><p className="text-xs text-muted leading-relaxed line-clamp-2">{d.summary}</p><div className="flex items-center gap-1 mt-3 text-xs text-accent">Explore <ChevronRight className="h-3 w-3" /></div></button>))}</div></section>
      {filteredFolk.length > 0 && (<section><h2 className="section-title text-xl text-accent mb-4">Folk & Regional Deities</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{filteredFolk.map((f) => (<button key={f.id} onClick={() => setSelected(f)} className="card p-5 text-left hover:border-[var(--accent)] transition-all hover:-translate-y-0.5"><div className="flex items-start justify-between gap-2 mb-2"><div><h3 className="font-semibold text-base">{f.name}</h3><p className="text-xs text-accent flex items-center gap-1"><MapPin className="h-3 w-3" /> {f.region}</p></div><SafetyBadge level={f.safety} compact /></div><p className="text-xs text-muted leading-relaxed line-clamp-3">{f.summary}</p></button>))}</div></section>)}
      <Modal open={!!selected} onClose={() => setSelected(null)} title={selected?.name || ''}>{selected && (<div className="space-y-4"><SafetyBadge level={selected.safety} /><p className="text-sm leading-relaxed">{selected.summary}</p>{'forms' in selected && selected.forms && selected.forms.length > 0 && (<div><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2">Forms</h4><div className="flex flex-wrap gap-2">{selected.forms.map((f, i) => (<span key={i} className="chip">{f}</span>))}</div></div>)}{'weapons' in selected && selected.weapons && selected.weapons.length > 0 && (<div><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2">Weapons</h4><div className="flex flex-wrap gap-2">{selected.weapons.map((w, i) => (<span key={i} className="chip"><Sword className="h-3 w-3" /> {w}</span>))}</div></div>)}{'mount' in selected && selected.mount && (<div><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2">Mount (Vahana)</h4><p className="text-sm">{selected.mount}</p></div>)}{'mantras' in selected && selected.mantras && selected.mantras.length > 0 && (<div><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2">Mantras</h4><div className="space-y-2">{selected.mantras.map((m, i) => (<div key={i} className="card-2 p-3"><p className="deva text-sm">{m}</p></div>))}</div></div>)}{'puranicRefs' in selected && selected.puranicRefs && (<div><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2">Puranic & Literary References</h4><ul className="text-sm space-y-1 list-disc list-inside text-muted">{selected.puranicRefs.map((r, i) => <li key={i}>{r}</li>)}</ul></div>)}{'festivals' in selected && selected.festivals && (<div><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2">Festivals</h4><div className="flex flex-wrap gap-2">{selected.festivals.map((f, i) => <span key={i} className="chip">{f}</span>)}</div></div>)}</div>)}</Modal>
    </div>
  );
}
