import { useState } from 'react';
import { PATH_RESULTS } from '@/data/content';
import type { PathResult } from '@/types';
import { ArrowRight, RotateCcw, Check } from 'lucide-react';

interface Question { q: string; options: { label: string; scores: Record<string, number> }[]; }
const QUESTIONS: Question[] = [
  { q: 'What draws you most in spiritual life?', options: [{ label: 'Loving devotion to a personal God', scores: { vaishnava: 3, shaiva: 0, shakta: 0, smarta: 1 } },{ label: 'Silent meditation and self-inquiry', scores: { vaishnava: 0, shaiva: 3, shakta: 0, smarta: 1 } },{ label: 'The power and energy of the Divine Mother', scores: { vaishnava: 0, shaiva: 0, shakta: 3, smarta: 1 } },{ label: 'A balanced approach honoring all forms', scores: { vaishnava: 1, shaiva: 1, shakta: 1, smarta: 3 } }] },
  { q: 'Which form of the divine feels most approachable?', options: [{ label: 'Krishna, Rama, or Narayana', scores: { vaishnava: 3, shaiva: 0, shakta: 0, smarta: 1 } },{ label: 'Shiva as the silent meditator or Nataraja', scores: { vaishnava: 0, shaiva: 3, shakta: 0, smarta: 1 } },{ label: 'Durga, Kali, or Lalita', scores: { vaishnava: 0, shaiva: 0, shakta: 3, smarta: 1 } },{ label: 'All deities as forms of the one Brahman', scores: { vaishnava: 1, shaiva: 1, shakta: 1, smarta: 3 } }] },
  { q: 'What is your primary spiritual temperament?', options: [{ label: 'Emotional, devotional, service-oriented', scores: { vaishnava: 3, shaiva: 0, shakta: 1, smarta: 1 } },{ label: 'Intellectual, contemplative, ascetic', scores: { vaishnava: 0, shaiva: 3, shakta: 0, smarta: 1 } },{ label: 'Dynamic, transformative, seeking inner power', scores: { vaishnava: 0, shaiva: 0, shakta: 3, smarta: 1 } },{ label: 'Harmonized, ritualistic, balanced', scores: { vaishnava: 1, shaiva: 1, shakta: 1, smarta: 3 } }] },
  { q: 'How do you prefer to pray?', options: [{ label: 'Singing the divine name (kirtan, bhajan)', scores: { vaishnava: 3, shaiva: 0, shakta: 1, smarta: 1 } },{ label: 'Silent japa and meditation', scores: { vaishnava: 1, shaiva: 3, shakta: 0, smarta: 1 } },{ label: 'With mantras, yantras, and ritual', scores: { vaishnava: 0, shaiva: 0, shakta: 3, smarta: 1 } },{ label: 'Through structured daily puja', scores: { vaishnava: 1, shaiva: 1, shakta: 1, smarta: 3 } }] },
  { q: 'What is your view on form vs. the formless?', options: [{ label: 'I need a personal form to relate to', scores: { vaishnava: 3, shaiva: 0, shakta: 1, smarta: 0 } },{ label: 'The formless is more real to me', scores: { vaishnava: 0, shaiva: 3, shakta: 0, smarta: 1 } },{ label: 'Form is the Mother; the formless is her power', scores: { vaishnava: 0, shaiva: 0, shakta: 3, smarta: 1 } },{ label: 'Both are valid expressions of the one Reality', scores: { vaishnava: 1, shaiva: 1, shakta: 1, smarta: 3 } }] },
  { q: 'Which lifestyle feels most aligned with your path?', options: [{ label: 'Devotional, community-oriented, joyful service', scores: { vaishnava: 3, shaiva: 0, shakta: 0, smarta: 1 } },{ label: 'Simple, meditative, introspective', scores: { vaishnava: 0, shaiva: 3, shakta: 0, smarta: 1 } },{ label: 'Disciplined, transformative, seeking to channel energy', scores: { vaishnava: 0, shaiva: 0, shakta: 3, smarta: 1 } },{ label: 'Regular, ritual-based, honoring all traditions', scores: { vaishnava: 1, shaiva: 1, shakta: 1, smarta: 3 } }] },
  { q: 'Which scripture resonates most with you?', options: [{ label: 'Bhagavad Gita, Srimad Bhagavatam', scores: { vaishnava: 3, shaiva: 0, shakta: 0, smarta: 1 } },{ label: 'Shiva Sutras, Upanishads', scores: { vaishnava: 0, shaiva: 3, shakta: 0, smarta: 1 } },{ label: 'Devi Mahatmyam, Soundarya Lahari', scores: { vaishnava: 0, shaiva: 0, shakta: 3, smarta: 1 } },{ label: 'All of the above equally', scores: { vaishnava: 1, shaiva: 1, shakta: 1, smarta: 3 } }] },
];

export function PathfinderPage() {
  const [stage, setStage] = useState(0);
  const [scores, setScores] = useState<Record<string, number>>({ vaishnava: 0, shaiva: 0, shakta: 0, smarta: 0 });
  const [result, setResult] = useState<PathResult | null>(null);
  const answer = (optionScores: Record<string, number>) => { const newScores = { ...scores }; for (const k in optionScores) newScores[k] += optionScores[k]; setScores(newScores); if (stage < QUESTIONS.length - 1) { setStage(stage + 1); } else { const sorted = Object.entries(newScores).sort((a, b) => b[1] - a[1]); const top = sorted[0][0]; const total = Object.values(newScores).reduce((a, b) => a + b, 0) || 1; const affinity = Math.round((newScores[top] / total) * 100); const base = PATH_RESULTS.find((p) => p.tradition === top)!; setResult({ ...base, affinity }); } };
  const restart = () => { setStage(0); setScores({ vaishnava: 0, shaiva: 0, shakta: 0, smarta: 0 }); setResult(null); };
  if (result) { return (<div className="space-y-6 animate-fadeIn max-w-2xl mx-auto"><div className="card p-8 text-center"><div className="h-16 w-16 rounded-full bg-gold/15 flex items-center justify-center mx-auto mb-4"><Check className="h-8 w-8 text-accent" /></div><h1 className="section-title text-2xl text-accent mb-2">Your Path</h1><p className="text-muted text-sm mb-6">{result.label}</p><div className="relative h-3 rounded-full bg-card2 overflow-hidden mb-2"><div className="absolute inset-y-0 left-0 bg-gold rounded-full transition-all" style={{ width: `${result.affinity}%` }} /></div><p className="text-sm text-accent mb-6">{result.affinity}% affinity</p><p className="text-sm leading-relaxed mb-6">{result.description}</p><div className="card-2 p-4 mb-4 text-left"><h3 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2">Starting Mantra</h3><p className="text-sm">{result.startingMantra}</p></div><div className="card-2 p-4 text-left"><h3 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2">Suggested Readings</h3><ul className="text-sm space-y-1 list-disc list-inside text-muted">{result.readings.map((r, i) => <li key={i}>{r}</li>)}</ul></div><button onClick={restart} className="btn-ghost mt-6 px-5 py-2.5 text-sm flex items-center gap-2 mx-auto"><RotateCcw className="h-4 w-4" /> Retake Quiz</button></div></div>); }
  const q = QUESTIONS[stage];
  return (<div className="space-y-6 animate-fadeIn max-w-2xl mx-auto"><div className="text-center"><h1 className="section-title text-3xl text-accent mb-2">Ishta & Path Finder</h1><p className="text-muted text-sm">A 7-stage evaluation of your spiritual temperament.</p></div><div className="flex items-center gap-1.5">{QUESTIONS.map((_, i) => (<div key={i} className={`h-1.5 flex-1 rounded-full ${i <= stage ? 'bg-gold' : 'bg-card2'}`} />))}</div><p className="text-xs text-muted text-center">Stage {stage + 1} of {QUESTIONS.length}</p><div className="card p-6"><h2 className="text-lg font-semibold mb-6">{q.q}</h2><div className="space-y-3">{q.options.map((opt, i) => (<button key={i} onClick={() => answer(opt.scores)} className="card-2 p-4 w-full text-left hover:border-[var(--accent)] transition-all flex items-center justify-between group"><span className="text-sm">{opt.label}</span><ArrowRight className="h-4 w-4 text-muted group-hover:text-accent transition-colors" /></button>))}</div></div></div>);
}
