import { useState, useEffect } from 'react';
import { PUJA_GUIDES } from '@/data/newcontent';
import { addToHistory } from '@/lib/storage';
import { Modal } from '@/components/Modal';
import { ChevronRight, Shield, ListChecks, AlertTriangle, Clock, Printer } from 'lucide-react';

export function PujaGuidesPage() {
  const [selected, setSelected] = useState<typeof PUJA_GUIDES[0] | null>(null);
  useEffect(() => { addToHistory('Puja Guides'); }, []);
  return (
    <div className="space-y-6 animate-fadeIn">
      <div><h1 className="section-title text-3xl text-accent mb-2">Puja Guides</h1><p className="text-muted text-sm">Step-by-step beginner-friendly guides for home worship. Each guide includes preparation, materials, the meaning behind every step, common mistakes, and a printable checklist.</p></div>
      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{PUJA_GUIDES.map((g) => (<button key={g.id} onClick={() => setSelected(g)} className="card p-5 text-left hover:border-[var(--accent)] transition-all hover:-translate-y-0.5 group"><div className="h-10 w-10 rounded-xl bg-card2 flex items-center justify-center mb-3 group-hover:shadow-glow"><Shield className="h-5 w-5 text-accent" /></div><h3 className="font-semibold mb-1">{g.title}</h3><p className="text-xs text-muted leading-relaxed line-clamp-2">{g.preparation[0]}</p><div className="flex items-center gap-1 mt-3 text-xs text-accent">Open Guide <ChevronRight className="h-3 w-3" /></div></button>))}</div>
      <Modal open={!!selected} onClose={() => setSelected(null)} title={selected?.title || ''}>{selected && (<div className="space-y-5"><div><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2">Preparation</h4><ul className="text-sm space-y-1 list-disc list-inside text-muted">{selected.preparation.map((p, i) => <li key={i}>{p}</li>)}</ul></div><div><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2">Required Materials</h4><div className="flex flex-wrap gap-1.5">{selected.materials.map((m, i) => <span key={i} className="chip text-[10px]">{m}</span>)}</div></div><div className="card-2 p-3"><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-1">Mental Preparation</h4><p className="text-sm leading-relaxed">{selected.mentalPrep}</p></div><div className="card-2 p-3"><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-1">Simple Sankalpa</h4><p className="text-sm leading-relaxed">{selected.sankalpa}</p></div><div><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2 flex items-center gap-1.5"><Clock className="h-3 w-3" /> Sequence & Meaning</h4><div className="space-y-2">{selected.steps.map((s, i) => (<div key={i} className="card-2 p-3"><div className="flex items-start gap-2"><span className="h-6 w-6 rounded-full bg-gold/15 flex items-center justify-center text-accent font-bold text-xs shrink-0">{i + 1}</span><div><p className="text-sm font-semibold">{s.name}</p><p className="text-xs text-muted mt-0.5">{s.meaning}</p></div></div></div>))}</div></div><div className="card-2 p-3 border-l-2 border-amber-500/50"><h4 className="text-xs font-semibold text-amber-400 uppercase tracking-wide mb-2 flex items-center gap-1.5"><AlertTriangle className="h-3 w-3" /> Common Mistakes to Avoid</h4><ul className="text-sm space-y-1 list-disc list-inside text-muted">{selected.commonMistakes.map((m, i) => <li key={i}>{m}</li>)}</ul></div><div className="card-2 p-3 border-l-2 border-emerald-500/50"><h4 className="text-xs font-semibold text-emerald-400 uppercase tracking-wide mb-1">Alternative Minimal Version</h4><p className="text-sm leading-relaxed">{selected.minimalVersion}</p></div><div><h4 className="text-xs font-semibold text-accent uppercase tracking-wide mb-2 flex items-center gap-1.5"><ListChecks className="h-3 w-3" /> Printable Checklist</h4><div className="card-2 p-4"><div className="space-y-2">{selected.checklist.map((c, i) => (<div key={i} className="flex items-center gap-2 text-sm"><span className="h-4 w-4 rounded border border-soft" />{c}</div>))}</div><button onClick={() => window.print()} className="btn-ghost px-4 py-2 text-xs mt-4 flex items-center gap-2"><Printer className="h-3.5 w-3.5" /> Print Checklist</button></div></div></div>)}</Modal>
    </div>
  );
}
