import { useState } from 'react';
import { MANTRAS, MUDRAS, ALTAR_LAYOUTS } from '@/data/content';
import { SafetyBadge, SafetyCard } from '@/components/SafetyBadge';
import { Modal } from '@/components/Modal';
import { saveSankalpa, getSankalpa } from '@/lib/storage';
import type { SafetyLevel, View } from '@/types';
import { Hand, Sparkles, LayoutGrid, FileText, Check } from 'lucide-react';

interface Props { onNavigate: (v: View) => void; }
type Filter = 'all' | SafetyLevel;

export function UpasanaPage({ onNavigate }: Props) {
  const [filter, setFilter] = useState<Filter>('all');
  const [sankalpaOpen, setSankalpaOpen] = useState(false);
  const [altarOpen, setAltarOpen] = useState(false);
  const [mudraOpen, setMudraOpen] = useState(false);
  const [sankalpaData, setSankalpaData] = useState(getSankalpa() || { name: '', gotra: '', location: '', tithi: '' });
  const [generated, setGenerated] = useState('');
  const filteredMantras = MANTRAS.filter((m) => filter === 'all' || m.safety === filter);
  const generateSankalpa = () => { saveSankalpa(sankalpaData); const today = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }); const text = `Sankalpa:\n\nOm Sri Ganeshaya Namah.\n\nDwitiya, Tritiya Chaturthi... (Tithi)\n${sankalpaData.tithi || '[Tithi]'}\n\n${today}\n\n${sankalpaData.name || '[Your Name]'}, of the ${sankalpaData.gotra || '[Gotra]'} gotra,\nresiding in ${sankalpaData.location || '[Your Location]'},\n\nWith the blessings of Sri Guru and the Lord,\nI undertake this sadhana for spiritual upliftment, peace, and welfare of all beings.\n\nOm Tat Sat.\n\n[Now begin your chosen japa or puja.]`; setGenerated(text); };
  return (
    <div className="space-y-6 animate-fadeIn">
      <div><h1 className="section-title text-3xl text-accent mb-2">Upasana Vault</h1><p className="text-muted text-sm">Safe home practices with clear guidance. Every practice carries a safety badge.</p></div>
      <div className="grid sm:grid-cols-3 gap-3"><SafetyCard level="green" /><SafetyCard level="amber" /><SafetyCard level="red" /></div>
      <div className="grid sm:grid-cols-3 gap-4"><button onClick={() => setSankalpaOpen(true)} className="card p-5 text-left hover:border-[var(--accent)] transition-all group"><div className="h-10 w-10 rounded-xl bg-card2 flex items-center justify-center mb-3 group-hover:shadow-glow"><FileText className="h-5 w-5 text-accent" /></div><h3 className="font-semibold mb-1">Sankalpa Generator</h3><p className="text-xs text-muted">Compile a proper Sankalpa statement for your daily prayer.</p></button><button onClick={() => setAltarOpen(true)} className="card p-5 text-left hover:border-[var(--accent)] transition-all group"><div className="h-10 w-10 rounded-xl bg-card2 flex items-center justify-center mb-3 group-hover:shadow-glow"><LayoutGrid className="h-5 w-5 text-accent" /></div><h3 className="font-semibold mb-1">Altar Setup Guides</h3><p className="text-xs text-muted">Visual layouts for Smarta, Vaishnava, Shaiva & Shakta altars.</p></button><button onClick={() => setMudraOpen(true)} className="card p-5 text-left hover:border-[var(--accent)] transition-all group"><div className="h-10 w-10 rounded-xl bg-card2 flex items-center justify-center mb-3 group-hover:shadow-glow"><Hand className="h-5 w-5 text-accent" /></div><h3 className="font-semibold mb-1">Mudra Library</h3><p className="text-xs text-muted">Visual guides for home mudras with meanings and benefits.</p></button></div>
      <div className="flex gap-2">{(['all', 'green', 'amber', 'red'] as Filter[]).map((f) => (<button key={f} onClick={() => setFilter(f)} className={`chip ${filter === f ? 'chip-active' : ''}`}>{f === 'all' ? 'All Practices' : f === 'green' ? 'Home Safe' : f === 'amber' ? 'Rules Apply' : 'Research Only'}</button>))}</div>
      <div className="grid sm:grid-cols-2 gap-4">{filteredMantras.map((m) => (<div key={m.id} className="card p-5"><div className="flex items-start justify-between gap-2 mb-3"><div><h3 className="font-semibold">{m.deity}</h3><p className="text-xs text-muted">Target: {m.count} repetitions</p></div><SafetyBadge level={m.safety} compact /></div><p className="deva text-lg mb-1">{m.sanskrit}</p><p className="iast text-sm text-accent mb-1">{m.iast}</p><p className="text-xs text-muted mb-3">{m.english}</p><button onClick={() => onNavigate('japa')} className="btn-ghost w-full py-2 text-xs flex items-center justify-center gap-1.5"><Sparkles className="h-3.5 w-3.5" /> Start Japa</button></div>))}</div>
      <Modal open={sankalpaOpen} onClose={() => setSankalpaOpen(false)} title="Sankalpa Generator"><div className="space-y-4"><p className="text-sm text-muted">Enter your details to compile a proper Sankalpa statement to begin your daily prayer.</p><div className="grid sm:grid-cols-2 gap-3"><div><label className="text-xs text-muted block mb-1">Your Name</label><input className="input-field" value={sankalpaData.name} onChange={(e) => setSankalpaData({ ...sankalpaData, name: e.target.value })} placeholder="e.g., Soham" /></div><div><label className="text-xs text-muted block mb-1">Gotra</label><input className="input-field" value={sankalpaData.gotra} onChange={(e) => setSankalpaData({ ...sankalpaData, gotra: e.target.value })} placeholder="e.g., Kashyapa" /></div><div><label className="text-xs text-muted block mb-1">Location</label><input className="input-field" value={sankalpaData.location} onChange={(e) => setSankalpaData({ ...sankalpaData, location: e.target.value })} placeholder="e.g., Kolkata, India" /></div><div><label className="text-xs text-muted block mb-1">Tithi (lunar day)</label><input className="input-field" value={sankalpaData.tithi} onChange={(e) => setSankalpaData({ ...sankalpaData, tithi: e.target.value })} placeholder="e.g., Shukla Paksha Dwitiya" /></div></div><button onClick={generateSankalpa} className="btn-primary w-full py-2.5 text-sm flex items-center justify-center gap-2"><Sparkles className="h-4 w-4" /> Generate Sankalpa</button>{generated && (<div className="card-2 p-4"><pre className="text-xs whitespace-pre-wrap font-sans leading-relaxed">{generated}</pre></div>)}</div></Modal>
      <Modal open={altarOpen} onClose={() => setAltarOpen(false)} title="Altar Setup Guides"><div className="space-y-4"><p className="text-sm text-muted">Each tradition has its own altar arrangement. Follow these to avoid energetic clashes between different deity forms.</p>{ALTAR_LAYOUTS.map((a) => (<div key={a.id} className="card-2 p-4"><h3 className="font-semibold text-accent mb-1">{a.name}</h3><p className="text-sm text-muted mb-3">{a.description}</p><div className="grid grid-cols-2 sm:grid-cols-3 gap-2 mb-3">{a.items.map((item, i) => (<div key={i} className="bg-[var(--bg)] rounded-lg p-2 text-center text-xs border border-soft">{item}</div>))}</div><p className="text-xs text-amber-400 flex items-start gap-1.5"><span className="font-semibold">Note:</span> {a.note}</p></div>))}</div></Modal>
      <Modal open={mudraOpen} onClose={() => setMudraOpen(false)} title="Mudra Library"><div className="space-y-4">{MUDRAS.map((m) => (<div key={m.id} className="card-2 p-4"><div className="flex items-center gap-3 mb-2"><div className="h-10 w-10 rounded-xl bg-gold/15 flex items-center justify-center"><Hand className="h-5 w-5 text-accent" /></div><div><h3 className="font-semibold">{m.name}</h3><p className="iast text-xs text-accent">{m.iast}</p></div></div><p className="text-sm mb-1"><span className="text-muted text-xs">Meaning:</span> {m.meaning}</p><p className="text-sm mb-2"><span className="text-muted text-xs">Benefits:</span> {m.benefits}</p><div><p className="text-xs text-muted mb-1">Steps:</p><ol className="text-sm space-y-1 list-decimal list-inside text-[var(--text)]">{m.steps.map((s, i) => <li key={i}>{s}</li>)}</ol></div></div>))}</div></Modal>
    </div>
  );
}
